# cluster.name: "docker-cluster"
# network.host: 0.0.0.0

discovery.type: single-node
# xpack.license.self_generated.type: basic

# xpack.security.authc:
#   anonymous:
#     username: metricbeat_anonymous_user
#     roles: superuser
#     authz_exception: true
